[project]
name = "spruch-api"
version = "1.0.0"
description = "Spruch-API generating random demotivating german quotes via get_random_quote endpoint."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.2.3",
]
