apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: spruch-frontend
    {{- include "spruch-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: spruch-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: spruch-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: spruch-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: IS_PROD
              value: {{ .Values.frontend.env.isProd | quote }}
            - name: QUOTE_ENDPOINT_URL
              value: "http://{{ .Release.Name }}-backend-svc:{{ .Values.backend.service.port }}/quote"