backend:
  replicaCount: 3
  image:
    repository: spruch-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  env:
    isProd: "1"
    quotePath: "./assets/spruch.json"

frontend:
  replicaCount: 3
  image:
    repository: spruch-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 8501
  env:
    isProd: "1"

ingress:
  enabled: true
  className: "nginx"
  host: "localhost"

ingress-nginx:
  enabled: true
  controller:
    hostPort:
      enabled: true
    terminationGracePeriodSeconds: 0
    service:
      type: "NodePort"
    nodeSelector:
      ingress-ready: "true"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        effect: "NoSchedule"
    publishService:
      enabled: false
    extraArgs:
      publish-status-address: "localhost"